# 网站设置
locale                   : "zh-CN"
title                    : "AI创未来"
title_separator          : "-"
subtitle                 : ""
name                     : "聪明的笨猪"
description              : "AI学习，AI分享，AI创意，AI编程"
url                      : # 填写您的GitHub Pages URL
baseurl                  : # 留空或填写子路径，如 "/blog"
repository               : "idkkk/rubiklife.github.io" # GitHub用户名/仓库名
teaser                   : # 默认的帖子题图
logo                     : # 网站logo路径
masthead_title           : # 覆盖网站标题显示的标题
breadcrumbs              : true # 显示面包屑导航
breadcrumb_home_label    : "首页"
breadcrumb_separator     : "/"
timezone                 : "Asia/Shanghai" # 设置东八区时间
date_format              : "%Y年%m月%d日 %H:%M"

# 网站主题设置
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# SEO相关
atom_feed:
  hide                   : true # 禁用默认的RSS链接
  path                   : "/feed.xml" # RSS feed路径
  title                  : "AI创未来 - 最新文章" # RSS标题

# Jekyll Feed 设置
feed:
  path: feed.xml
  posts_limit: 20
  excerpt_only: false
  categories:
    - 技术
    - 教程

# 站点搜索设置
search                   : true
search_full_content      : true
search_provider          : lunr # lunr (默认), algolia, google

# 社交分享链接
twitter:
  username               : 
facebook:
  username               : 
  app_id                 : 
  publisher              : 
og_image                 : # Open Graph图片

# 社交账号链接
social:
  links:
    - "https://x.com/cn_zealot"
    - "https://github.com/idkkk"

# 分析设置
analytics:
  provider               : "google-gtag" # false (默认), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-7FWZY2QFBD" # 替换为您的Google Analytics跟踪ID
    anonymize_ip         : false # true, false (默认)

# 评论系统设置
comments:
  provider               : "giscus" # false (默认), "disqus", "discourse", "facebook", "staticman", "utterances", "giscus", "custom"
  giscus:
    repo                 : "rubiklife/rubiklife.github.io" # GitHub username/repo-name
    repo_id              : "R_kgDOOZD27g" # 从giscus.app获取
    category             : "Announcements" # 必须与giscus.app上配置的一致
    category_id          : "DIC_kwDOOZD27s4Cpdf3" # 从giscus.app获取
    discussion_term      : "pathname" # pathname (默认), url, title, og:title
    reactions_enabled    : "1" # '1' for enabled (默认), '0' for disabled
    theme                : "light" # 'light' (默认), 'dark', 'dark_dimmed', 'transparent_dark', 'preferred_color_scheme'
    language             : "zh-CN" # en, zh-CN, zh-TW等

# 站点作者信息
author:
  name             : "聪明的笨猪"
  avatar           : # 头像路径
  bio              : ""
  location         : "HangZhou, CN"
  email            : 
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:xiajinxin@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/idkkk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/cn_zealot"

# 页脚链接
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/idkkk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/cn_zealot"
    - label: "RSS"
      icon: "fas fa-fw fa-rss-square"
      url: "/feed.xml"

# 导入Minimal Mistakes主题
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# 压缩HTML、CSS和JS
compress_html:
  clippings: all
  ignore:
    envs: development

# 文章默认设置
defaults:
  # 所有文章
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      show_date: true
  # 所有页面
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# 站点导航
include:
  - _pages

# 编译排除项
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

# 分页设置
paginate: 10
paginate_path: /page:num/

# 分类和标签页面设置
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/